#!/bin/sh
APPBASE="/home/carmichael/Greenfoot/greenfoot"
JAVAPATH="/usr/lib/jvm/java-6-openjdk-amd64"
CP="$APPBASE/lib/bluej.jar:$JAVAPATH/lib/tools.jar"
"$JAVAPATH/bin/java" -cp "$CP" bluej.Boot -greenfoot=true -bluej.compiler.showunchecked=false "$@"
